Repository SOPT-29th-Joint-Seminar-8/NaverBlog-iOS, pull requests merged in 2021-12, with the labels that each got.

#8 [Feat] Feed UI 구현
  .gitattributes
  .gitignore
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.pbxproj
  NaverBlog-iOS/NaverBlog-iOS/Resources/Assets/Feed.xcassets/icStatus.imageset/Contents.json
  NaverBlog-iOS/NaverBlog-iOS/Resources/Assets/Feed.xcassets/icStatus.imageset/icStatus.png
  NaverBlog-iOS/NaverBlog-iOS/Resources/Assets/Feed.xcassets/icStatus.imageset/icStatus@2x.png
  NaverBlog-iOS/NaverBlog-iOS/Resources/Assets/Feed.xcassets/icStatus.imageset/icStatus@3x.png
  NaverBlog-iOS/NaverBlog-iOS/Resources/Consts/Image.swift
  NaverBlog-iOS/NaverBlog-iOS/Resources/Extensions/Formatter+.swift
  NaverBlog-iOS/NaverBlog-iOS/Resources/Extensions/NotificationCenter+.swift
  NaverBlog-iOS/NaverBlog-iOS/Resources/Supports/SceneDelegate.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/FeedVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedContent.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedHeader.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedManager.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/VCs/CustomTBC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/VCs/FeedVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/Base.lproj/Feed.storyboard
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/BodyViews/FeedTVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/BodyViews/FeedTVC.xib
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/HeaderViews/FeedTableHeaderView.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/HeaderViews/FeedTableHeaderView.xib
Labels: 승현

#15 [Feat] Feed UI 서버 통신
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.pbxproj
  NaverBlog-iOS/NaverBlog-iOS/Resources/Consts/API.swift
  NaverBlog-iOS/NaverBlog-iOS/Resources/Extensions/Formatter+.swift
  NaverBlog-iOS/NaverBlog-iOS/Resources/Protocols/ReloadData.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedContent.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedManager.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedNetworkManager.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Models/FeedNetworkModel.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/VCs/FeedVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/BodyViews/FeedTVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/HeaderViews/FeedTableHeaderView.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Feed/Views/HeaderViews/FeedTableHeaderView.xib
  NaverBlog-iOS/NaverBlog-iOS/Sources/Notification/Notification.storyboard
Labels: 승현

#16 Feature/#12
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.pbxproj
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.xcworkspace/xcuserdata/gimsoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  NaverBlog-iOS/NaverBlog-iOS/Resources/Supports/SceneDelegate.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Models/MyPageDetailResponse.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Models/MyPageResponse.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Services/MyPageDetailService.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Services/MyPageService.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/VCs/MyPageDetailVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/VCs/MyPageVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Views/Cells/MyPageTVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Views/CustomNavigationBarView.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Views/HeaderViews/MyPageTableHeaderView.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/MyPage/Views/HeaderViews/MyPageTableHeaderView.xib
Labels: 소연

#17 Feature/#13
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.pbxproj
  NaverBlog-iOS/NaverBlog-iOS.xcodeproj/project.xcworkspace/xcuserdata/baeeunseo.xcuserdatad/UserInterfaceState.xcuserstate
  NaverBlog-iOS/NaverBlog-iOS/Resources/Consts/API.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/Comment.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/CommentData.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/CommentDataModel.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/CommentResponse.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/ReplyComment.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Models/ReplyCommentDataModel.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Network/CommentManager.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/ViewControllers/RecommendVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Views/Cells/CommentTVC.swift
  NaverBlog-iOS/NaverBlog-iOS/Sources/Recommend/Views/Storyboards/CommentTVC.xib
  NaverBlog-iOS/Podfile.lock
Labels: 은서
